version: '3.8'

services:
  api:
    container_name: kanban-api
    build: .
    env_file: ".env"
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
